
- hosts: all

  roles:
    - role: nginx,
      nginx_http_params:
        sendfile: "on"
        access_log: "/var/log/nginx/access.log"
        nginx_sites:
        - server:
           file_name: bar
           listen: 8001
           keepalive_timeout: 5
           location1:
             name: "/"
             try_files: "$uri @proxy_to_app"
           location2:
             name: "@proxy_to_app"
             proxy_set_header: "X-Forwarded-For $proxy_add_x_forwarded_for"
             proxy_set_header: "Host $http_host"
             proxy_redirect: off
             proxy_pass: http://app_server

     - role: telusdigital.python
        python_requirements_file: mysite/requirements.txt
