
- hosts: all
  become: true

  tasks:
    - name: installing repo for Java 8 in Ubuntu
      apt_repository: repo='ppa:openjdk-r/ppa'

- hosts: all
  become: true

  roles:
    - role: telusdigital.python
      python_requirements_file: "/vagrant/mysite/requirements.txt"

    - role: jdauphant.nginx
      nginx_http_params:
        - sendfile "on"
        - access_log "/var/log/nginx/access.log"
      nginx_sites:
        bar:
           - listen 5000
           - location / { proxy_pass http://127.0.0.1:8000; }
           - location /nginx_status_page { stub_status on; }
      nginx_configs:
        proxy:
           - proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for
           - proxy_set_header Host $http_host

    - role: tersmitten.supervisor
      supervisor_programs_present:
        gunicorn:
          command: 'gunicorn -w 3 --worker-class=gevent --name=my_web_app --statsd-host=localhost:8125 mysite.wsgi'
          directory: /vagrant/mysite
          autostart: true
          autorestart: true
          startretries: 3
          stdout_logfile: /tmp/foo.out
          stdout_logfile_maxbytes: 0
          stderr_logfile: /tmp/foo.err
          stderr_logfile_maxbytes: 0
          user: root
          numprocs: 1
          process_name: '%(program_name)s-%(process_num)s'

      supervisor_groups_present:
        app_server:
          programs:
            - gunicorn
          priority: 10

    - role: geerlingguy.java
      java_packages:
        - openjdk-8-jdk
      java_home:

    - role: geerlingguy.solr
